"""
Sandbox environment for safe code execution and testing.

This module provides a secure sandboxed environment for executing code
generated by agents, ensuring isolation and security.
"""

import asyncio
import subprocess
import tempfile
import os
import shutil
import logging
from typing import Dict, Any, Optional, List
from pathlib import Path
import json
import sys
from datetime import datetime, timedelta

logger = logging.getLogger(__name__)

class SandboxExecutionResult:
    """Result of sandboxed code execution."""
    
    def __init__(self, success: bool, stdout: str = "", stderr: str = "", 
                 execution_time: float = 0.0, error: Optional[str] = None):
        self.success = success
        self.stdout = stdout
        self.stderr = stderr
        self.execution_time = execution_time
        self.error = error
        self.timestamp = datetime.now()

class Sandbox:
    """Secure sandbox environment for code execution."""
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """Initialize the sandbox."""
        self.config = config or {}
        self.max_execution_time = self.config.get("max_execution_time", 30.0)  # seconds
        self.max_memory_mb = self.config.get("max_memory_mb", 512)
        self.allowed_languages = self.config.get("allowed_languages", 
                                                ["python", "javascript", "java", "cpp"])
        self.temp_dir = None
        self.logger = logging.getLogger("sandbox")
        
    async def __aenter__(self):
        """Async context manager entry."""
        await self.setup()
        return self
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Async context manager exit."""
        await self.cleanup()
    
    async def setup(self) -> None:
        """Setup the sandbox environment."""
        self.temp_dir = tempfile.mkdtemp(prefix="agent_sandbox_")
        self.logger.info(f"Sandbox created at: {self.temp_dir}")
    
    async def cleanup(self) -> None:
        """Cleanup the sandbox environment."""
        if self.temp_dir and os.path.exists(self.temp_dir):
            try:
                shutil.rmtree(self.temp_dir)
                self.logger.info(f"Sandbox cleaned up: {self.temp_dir}")
            except Exception as e:
                self.logger.error(f"Failed to cleanup sandbox: {str(e)}")
    
    async def execute_code(self, code: str, language: str, 
                          input_data: Optional[str] = None) -> SandboxExecutionResult:
        """
        Execute code in the sandbox.
        
        Args:
            code: Code to execute
            language: Programming language (python, javascript, java, cpp)
            input_data: Optional input data for the code
            
        Returns:
            SandboxExecutionResult with execution details
        """
        if language not in self.allowed_languages:
            return SandboxExecutionResult(
                success=False,
                error=f"Language '{language}' not supported. Allowed: {self.allowed_languages}"
            )
        
        if not self.temp_dir:
            await self.setup()
        
        start_time = datetime.now()
        
        try:
            # Prepare execution environment
            exec_result = await self._execute_with_timeout(
                code, language, input_data
            )
            
            execution_time = (datetime.now() - start_time).total_seconds()
            
            return SandboxExecutionResult(
                success=exec_result.returncode == 0,
                stdout=exec_result.stdout,
                stderr=exec_result.stderr,
                execution_time=execution_time
            )
            
        except asyncio.TimeoutError:
            execution_time = (datetime.now() - start_time).total_seconds()
            return SandboxExecutionResult(
                success=False,
                execution_time=execution_time,
                error=f"Execution timed out after {self.max_execution_time} seconds"
            )
        except Exception as e:
            execution_time = (datetime.now() - start_time).total_seconds()
            return SandboxExecutionResult(
                success=False,
                execution_time=execution_time,
                error=f"Execution failed: {str(e)}"
            )
    
    async def _execute_with_timeout(self, code: str, language: str, 
                                   input_data: Optional[str] = None) -> subprocess.CompletedProcess:
        """Execute code with timeout protection."""
        
        if language == "python":
            return await self._execute_python(code, input_data)
        elif language == "javascript":
            return await self._execute_javascript(code, input_data)
        elif language == "java":
            return await self._execute_java(code, input_data)
        elif language == "cpp":
            return await self._execute_cpp(code, input_data)
        else:
            raise ValueError(f"Unsupported language: {language}")
    
    async def _execute_python(self, code: str, input_data: Optional[str] = None) -> subprocess.CompletedProcess:
        """Execute Python code."""
        script_file = os.path.join(self.temp_dir, "script.py")
        
        # Write code to file
        with open(script_file, 'w') as f:
            f.write(code)
        
        # Prepare command
        cmd = [
            sys.executable,  # Current Python interpreter
            script_file
        ]
        
        # Execute with timeout
        try:
            process = await asyncio.wait_for(
                asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    stdin=asyncio.subprocess.PIPE if input_data else None,
                    cwd=self.temp_dir,
                    env=self._get_sandbox_env()
                ),
                timeout=self.max_execution_time
            )
            
            stdout, stderr = await process.communicate(
                input=input_data.encode() if input_data else None
            )
            
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=process.returncode,
                stdout=stdout.decode(),
                stderr=stderr.decode()
            )
            
        except asyncio.TimeoutError:
            # Kill the process if it's still running
            if 'process' in locals():
                process.terminate()
                await process.wait()
            raise
    
    async def _execute_javascript(self, code: str, input_data: Optional[str] = None) -> subprocess.CompletedProcess:
        """Execute JavaScript code using Node.js."""
        script_file = os.path.join(self.temp_dir, "script.js")
        
        # Write code to file
        with open(script_file, 'w') as f:
            f.write(code)
        
        # Check if Node.js is available
        node_cmd = shutil.which("node")
        if not node_cmd:
            raise RuntimeError("Node.js not found. Please install Node.js to execute JavaScript code.")
        
        cmd = [node_cmd, script_file]
        
        try:
            process = await asyncio.wait_for(
                asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    stdin=asyncio.subprocess.PIPE if input_data else None,
                    cwd=self.temp_dir,
                    env=self._get_sandbox_env()
                ),
                timeout=self.max_execution_time
            )
            
            stdout, stderr = await process.communicate(
                input=input_data.encode() if input_data else None
            )
            
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=process.returncode,
                stdout=stdout.decode(),
                stderr=stderr.decode()
            )
            
        except asyncio.TimeoutError:
            if 'process' in locals():
                process.terminate()
                await process.wait()
            raise
    
    async def _execute_java(self, code: str, input_data: Optional[str] = None) -> subprocess.CompletedProcess:
        """Execute Java code."""
        # Create Java file
        java_file = os.path.join(self.temp_dir, "Main.java")
        
        # Write code to file
        with open(java_file, 'w') as f:
            f.write(code)
        
        # Check if Java compiler is available
        javac_cmd = shutil.which("javac")
        java_cmd = shutil.which("java")
        
        if not javac_cmd or not java_cmd:
            raise RuntimeError("Java not found. Please install JDK to execute Java code.")
        
        # Compile Java code
        compile_result = await asyncio.wait_for(
            asyncio.create_subprocess_exec(
                javac_cmd, java_file,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=self.temp_dir
            ),
            timeout=self.max_execution_time
        )
        
        compile_stdout, compile_stderr = await compile_result.communicate()
        
        if compile_result.returncode != 0:
            return subprocess.CompletedProcess(
                args=[javac_cmd, java_file],
                returncode=compile_result.returncode,
                stdout=compile_stdout.decode(),
                stderr=compile_stderr.decode()
            )
        
        # Run compiled Java code
        cmd = [java_cmd, "-cp", self.temp_dir, "Main"]
        
        try:
            process = await asyncio.wait_for(
                asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    stdin=asyncio.subprocess.PIPE if input_data else None,
                    cwd=self.temp_dir,
                    env=self._get_sandbox_env()
                ),
                timeout=self.max_execution_time
            )
            
            stdout, stderr = await process.communicate(
                input=input_data.encode() if input_data else None
            )
            
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=process.returncode,
                stdout=stdout.decode(),
                stderr=stderr.decode()
            )
            
        except asyncio.TimeoutError:
            if 'process' in locals():
                process.terminate()
                await process.wait()
            raise
    
    async def _execute_cpp(self, code: str, input_data: Optional[str] = None) -> subprocess.CompletedProcess:
        """Execute C++ code."""
        # Create C++ file
        cpp_file = os.path.join(self.temp_dir, "program.cpp")
        executable_file = os.path.join(self.temp_dir, "program")
        
        # Write code to file
        with open(cpp_file, 'w') as f:
            f.write(code)
        
        # Check if C++ compiler is available
        gxx_cmd = shutil.which("g++")
        if not gxx_cmd:
            raise RuntimeError("g++ compiler not found. Please install g++ to execute C++ code.")
        
        # Compile C++ code
        compile_result = await asyncio.wait_for(
            asyncio.create_subprocess_exec(
                gxx_cmd, cpp_file, "-o", executable_file,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                cwd=self.temp_dir
            ),
            timeout=self.max_execution_time
        )
        
        compile_stdout, compile_stderr = await compile_result.communicate()
        
        if compile_result.returncode != 0:
            return subprocess.CompletedProcess(
                args=[gxx_cmd, cpp_file, "-o", executable_file],
                returncode=compile_result.returncode,
                stdout=compile_stdout.decode(),
                stderr=compile_stderr.decode()
            )
        
        # Run compiled C++ code
        cmd = [executable_file]
        
        try:
            process = await asyncio.wait_for(
                asyncio.create_subprocess_exec(
                    *cmd,
                    stdout=asyncio.subprocess.PIPE,
                    stderr=asyncio.subprocess.PIPE,
                    stdin=asyncio.subprocess.PIPE if input_data else None,
                    cwd=self.temp_dir,
                    env=self._get_sandbox_env()
                ),
                timeout=self.max_execution_time
            )
            
            stdout, stderr = await process.communicate(
                input=input_data.encode() if input_data else None
            )
            
            return subprocess.CompletedProcess(
                args=cmd,
                returncode=process.returncode,
                stdout=stdout.decode(),
                stderr=stderr.decode()
            )
            
        except asyncio.TimeoutError:
            if 'process' in locals():
                process.terminate()
                await process.wait()
            raise
    
    def _get_sandbox_env(self) -> Dict[str, str]:
        """Get sandbox environment variables."""
        env = os.environ.copy()
        
        # Restrict some environment variables for security
        restricted_vars = [
            "HOME", "USER", "USERNAME", "USERPROFILE",
            "PATH", "SHELL", "TERM", "DISPLAY"
        ]
        
        for var in restricted_vars:
            env.pop(var, None)
        
        # Set minimal safe environment
        env.update({
            "PATH": "/usr/bin:/bin",  # Minimal PATH
            "PYTHONPATH": "",  # Clear Python path
            "PYTHONHOME": "",  # Clear Python home
        })
        
        return env
    
    async def validate_code(self, code: str, language: str) -> Dict[str, Any]:
        """
        Validate code syntax without executing it.
        
        Args:
            code: Code to validate
            language: Programming language
            
        Returns:
            Validation result with syntax check
        """
        validation_result = {
            "valid": True,
            "syntax_errors": [],
            "warnings": []
        }
        
        try:
            if language == "python":
                validation_result.update(await self._validate_python_syntax(code))
            elif language == "javascript":
                validation_result.update(await self._validate_javascript_syntax(code))
            elif language == "java":
                validation_result.update(await self._validate_java_syntax(code))
            elif language == "cpp":
                validation_result.update(await self._validate_cpp_syntax(code))
            else:
                validation_result["valid"] = False
                validation_result["syntax_errors"].append(f"Unsupported language: {language}")
                
        except Exception as e:
            validation_result["valid"] = False
            validation_result["syntax_errors"].append(f"Validation error: {str(e)}")
        
        return validation_result
    
    async def _validate_python_syntax(self, code: str) -> Dict[str, Any]:
        """Validate Python syntax."""
        try:
            compile(code, '<string>', 'exec')
            return {"valid": True, "syntax_errors": [], "warnings": []}
        except SyntaxError as e:
            return {
                "valid": False,
                "syntax_errors": [f"Line {e.lineno}: {e.msg}"],
                "warnings": []
            }
    
    async def _validate_javascript_syntax(self, code: str) -> Dict[str, Any]:
        """Validate JavaScript syntax (basic check)."""
        # Basic syntax validation - in a real implementation, 
        # you might use a proper JavaScript parser
        warnings = []
        
        # Check for basic syntax issues
        if code.count("{") != code.count("}"):
            warnings.append("Mismatched braces")
        
        if code.count("(") != code.count(")"):
            warnings.append("Mismatched parentheses")
        
        return {
            "valid": len(warnings) == 0,
            "syntax_errors": warnings,
            "warnings": []
        }
    
    async def _validate_java_syntax(self, code: str) -> Dict[str, Any]:
        """Validate Java syntax (basic check)."""
        warnings = []
        
        # Basic Java syntax checks
        if "class" not in code:
            warnings.append("No class definition found")
        
        if "public static void main" not in code and "public static void main(String[] args)" not in code:
            warnings.append("No main method found")
        
        return {
            "valid": len(warnings) == 0,
            "syntax_errors": [],
            "warnings": warnings
        }
    
    async def _validate_cpp_syntax(self, code: str) -> Dict[str, Any]:
        """Validate C++ syntax (basic check)."""
        warnings = []
        
        # Basic C++ syntax checks
        if "#include" not in code:
            warnings.append("No include directives found")
        
        if "int main" not in code:
            warnings.append("No main function found")
        
        return {
            "valid": len(warnings) == 0,
            "syntax_errors": [],
            "warnings": warnings
        }
    
    def get_execution_stats(self) -> Dict[str, Any]:
        """Get sandbox execution statistics."""
        return {
            "max_execution_time": self.max_execution_time,
            "max_memory_mb": self.max_memory_mb,
            "allowed_languages": self.allowed_languages,
            "temp_directory": self.temp_dir,
            "is_active": self.temp_dir is not None and os.path.exists(self.temp_dir)
        }
